// Monsoon Assistant — Supabase/PostgreSQL Database Type Definitions
// Single source of truth for all DB types
// Generated by: supabase gen types typescript --project-id $SUPABASE_PROJECT_ID

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          phone: string;
          language: string;
          dialect: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          phone: string;
          language?: string;
          dialect?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          phone?: string;
          language?: string;
          dialect?: string | null;
          created_at?: string;
        };
      };
      families: {
        Row: {
          id: string;
          primary_member: string;
          address: string | null;
          lat: number | null;
          lng: number | null;
          district: string | null;
          ward: string | null;
          hazard_zones: string[] | null;
          housing_type: string | null;
          vulnerability_score: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          primary_member: string;
          address?: string | null;
          lat?: number | null;
          lng?: number | null;
          district?: string | null;
          ward?: string | null;
          hazard_zones?: string[] | null;
          housing_type?: string | null;
          vulnerability_score?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          primary_member?: string;
          address?: string | null;
          lat?: number | null;
          lng?: number | null;
          district?: string | null;
          ward?: string | null;
          hazard_zones?: string[] | null;
          housing_type?: string | null;
          vulnerability_score?: number | null;
          created_at?: string;
        };
      };
      family_members: {
        Row: {
          id: string;
          family_id: string;
          profile_id: string;
          relation: string | null;
          age: number | null;
          medical_conditions: string[] | null;
          is_vulnerable: boolean;
        };
        Insert: {
          id?: string;
          family_id: string;
          profile_id: string;
          relation?: string | null;
          age?: number | null;
          medical_conditions?: string[] | null;
          is_vulnerable?: boolean;
        };
        Update: {
          id?: string;
          family_id?: string;
          profile_id?: string;
          relation?: string | null;
          age?: number | null;
          medical_conditions?: string[] | null;
          is_vulnerable?: boolean;
        };
      };
      preparedness_plans: {
        Row: {
          id: string;
          family_id: string;
          phase: 'pre_monsoon' | 'active_monsoon' | 'post_monsoon';
          generated_by: string | null;
          genai_prompt_hash: string | null;
          risk_score_at_generation: number | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          phase: 'pre_monsoon' | 'active_monsoon' | 'post_monsoon';
          generated_by?: string | null;
          genai_prompt_hash?: string | null;
          risk_score_at_generation?: number | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          family_id?: string;
          phase?: 'pre_monsoon' | 'active_monsoon' | 'post_monsoon';
          generated_by?: string | null;
          genai_prompt_hash?: string | null;
          risk_score_at_generation?: number | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      checklist_items: {
        Row: {
          id: string;
          plan_id: string;
          item_text: string;
          item_text_localized: Json | null;
          priority: 'critical' | 'high' | 'medium' | 'low';
          category: string | null;
          phase_applicability: string[] | null;
          is_completed: boolean;
          completed_at: string | null;
          sort_order: number;
        };
        Insert: {
          id?: string;
          plan_id: string;
          item_text: string;
          item_text_localized?: Json | null;
          priority?: 'critical' | 'high' | 'medium' | 'low';
          category?: string | null;
          phase_applicability?: string[] | null;
          is_completed?: boolean;
          completed_at?: string | null;
          sort_order?: number;
        };
        Update: {
          id?: string;
          plan_id?: string;
          item_text?: string;
          item_text_localized?: Json | null;
          priority?: 'critical' | 'high' | 'medium' | 'low';
          category?: string | null;
          phase_applicability?: string[] | null;
          is_completed?: boolean;
          completed_at?: string | null;
          sort_order?: number;
        };
      };
      weather_alerts: {
        Row: {
          id: string;
          source: 'IMD' | 'CWC' | 'ULB' | 'MOCK';
          alert_type: string | null;
          severity: 'watch' | 'alert' | 'warning';
          districts: string[] | null;
          title: string | null;
          description: string | null;
          instruction: string | null;
          valid_from: string;
          valid_until: string;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          source: 'IMD' | 'CWC' | 'ULB' | 'MOCK';
          alert_type?: string | null;
          severity: 'watch' | 'alert' | 'warning';
          districts?: string[] | null;
          title?: string | null;
          description?: string | null;
          instruction?: string | null;
          valid_from: string;
          valid_until: string;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          source?: 'IMD' | 'CWC' | 'ULB' | 'MOCK';
          alert_type?: string | null;
          severity?: 'watch' | 'alert' | 'warning';
          districts?: string[] | null;
          title?: string | null;
          description?: string | null;
          instruction?: string | null;
          valid_from?: string;
          valid_until?: string;
          metadata?: Json | null;
          created_at?: string;
        };
      };
      localized_alerts: {
        Row: {
          id: string;
          weather_alert_id: string;
          family_id: string;
          language: string;
          title_localized: string | null;
          description_localized: string | null;
          action_items: string[] | null;
          risk_score: number | null;
          generated_at: string;
          read_at: string | null;
        };
        Insert: {
          id?: string;
          weather_alert_id: string;
          family_id: string;
          language: string;
          title_localized?: string | null;
          description_localized?: string | null;
          action_items?: string[] | null;
          risk_score?: number | null;
          generated_at?: string;
          read_at?: string | null;
        };
        Update: {
          id?: string;
          weather_alert_id?: string;
          family_id?: string;
          language?: string;
          title_localized?: string | null;
          description_localized?: string | null;
          action_items?: string[] | null;
          risk_score?: number | null;
          generated_at?: string;
          read_at?: string | null;
        };
      };
      shelters: {
        Row: {
          id: string;
          name: string;
          address: string | null;
          lat: number;
          lng: number;
          district: string | null;
          ward: string | null;
          capacity: number | null;
          current_occupancy: number;
          facilities: Json | null;
          managing_authority: string | null;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          name: string;
          address?: string | null;
          lat: number;
          lng: number;
          district?: string | null;
          ward?: string | null;
          capacity?: number | null;
          current_occupancy?: number;
          facilities?: Json | null;
          managing_authority?: string | null;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          name?: string;
          address?: string | null;
          lat?: number;
          lng?: number;
          district?: string | null;
          ward?: string | null;
          capacity?: number | null;
          current_occupancy?: number;
          facilities?: Json | null;
          managing_authority?: string | null;
          is_active?: boolean;
        };
      };
      evacuation_routes: {
        Row: {
          id: string;
          from_lat: number;
          from_lng: number;
          to_shelter_id: string;
          waypoints: Json | null;
          distance_km: number | null;
          duration_min: number | null;
          road_condition: string | null;
          suitable_for: 'vehicle' | 'pedestrian' | 'both' | null;
          last_updated: string;
        };
        Insert: {
          id?: string;
          from_lat: number;
          from_lng: number;
          to_shelter_id: string;
          waypoints?: Json | null;
          distance_km?: number | null;
          duration_min?: number | null;
          road_condition?: string | null;
          suitable_for?: 'vehicle' | 'pedestrian' | 'both' | null;
          last_updated?: string;
        };
        Update: {
          id?: string;
          from_lat?: number;
          from_lng?: number;
          to_shelter_id?: string;
          waypoints?: Json | null;
          distance_km?: number | null;
          duration_min?: number | null;
          road_condition?: string | null;
          suitable_for?: 'vehicle' | 'pedestrian' | 'both' | null;
          last_updated?: string;
        };
      };
      sos_requests: {
        Row: {
          id: string;
          profile_id: string;
          family_id: string | null;
          lat: number;
          lng: number;
          emergency_type: 'medical' | 'trapped' | 'evacuation' | 'other';
          description: string | null;
          status: 'active' | 'responded' | 'resolved' | 'false_alarm';
          created_at: string;
          resolved_at: string | null;
        };
        Insert: {
          id?: string;
          profile_id: string;
          family_id?: string | null;
          lat: number;
          lng: number;
          emergency_type: 'medical' | 'trapped' | 'evacuation' | 'other';
          description?: string | null;
          status?: 'active' | 'responded' | 'resolved' | 'false_alarm';
          created_at?: string;
          resolved_at?: string | null;
        };
        Update: {
          id?: string;
          profile_id?: string;
          family_id?: string | null;
          lat?: number;
          lng?: number;
          emergency_type?: 'medical' | 'trapped' | 'evacuation' | 'other';
          description?: string | null;
          status?: 'active' | 'responded' | 'resolved' | 'false_alarm';
          created_at?: string;
          resolved_at?: string | null;
        };
      };
      community_reports: {
        Row: {
          id: string;
          profile_id: string;
          lat: number;
          lng: number;
          report_type: 'waterlogging' | 'road_closure' | 'landslide' | 'shelter_status' | 'power_outage';
          severity: 'low' | 'medium' | 'high' | 'critical';
          description: string | null;
          photo_url: string | null;
          verification_status: 'unverified' | 'verified' | 'disputed';
          upvotes: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          lat: number;
          lng: number;
          report_type: 'waterlogging' | 'road_closure' | 'landslide' | 'shelter_status' | 'power_outage';
          severity: 'low' | 'medium' | 'high' | 'critical';
          description?: string | null;
          photo_url?: string | null;
          verification_status?: 'unverified' | 'verified' | 'disputed';
          upvotes?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          lat?: number;
          lng?: number;
          report_type?: 'waterlogging' | 'road_closure' | 'landslide' | 'shelter_status' | 'power_outage';
          severity?: 'low' | 'medium' | 'high' | 'critical';
          description?: string | null;
          photo_url?: string | null;
          verification_status?: 'unverified' | 'verified' | 'disputed';
          upvotes?: number;
          created_at?: string;
        };
      };
      offline_cache_manifests: {
        Row: {
          id: string;
          profile_id: string;
          device_id: string | null;
          checklist_items: Json | null;
          evacuation_routes: Json | null;
          shelters: Json | null;
          emergency_contacts: Json | null;
          last_synced: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          device_id?: string | null;
          checklist_items?: Json | null;
          evacuation_routes?: Json | null;
          shelters?: Json | null;
          emergency_contacts?: Json | null;
          last_synced?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          device_id?: string | null;
          checklist_items?: Json | null;
          evacuation_routes?: Json | null;
          shelters?: Json | null;
          emergency_contacts?: Json | null;
          last_synced?: string;
        };
      };
      risk_score_history: {
        Row: {
          id: string;
          family_id: string;
          score: number;
          factors: Json | null;
          recorded_at: string;
        };
        Insert: {
          id?: string;
          family_id: string;
          score: number;
          factors?: Json | null;
          recorded_at?: string;
        };
        Update: {
          id?: string;
          family_id?: string;
          score?: number;
          factors?: Json | null;
          recorded_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      phase: 'pre_monsoon' | 'active_monsoon' | 'post_monsoon';
      priority: 'critical' | 'high' | 'medium' | 'low';
      alert_severity: 'watch' | 'alert' | 'warning';
      emergency_type: 'medical' | 'trapped' | 'evacuation' | 'other';
      sos_status: 'active' | 'responded' | 'resolved' | 'false_alarm';
      report_type: 'waterlogging' | 'road_closure' | 'landslide' | 'shelter_status' | 'power_outage';
      report_severity: 'low' | 'medium' | 'high' | 'critical';
      verification_status: 'unverified' | 'verified' | 'disputed';
      road_condition: 'good' | 'waterlogged' | 'blocked' | 'unknown';
      suitable_for: 'vehicle' | 'pedestrian' | 'both';
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

// Json type used throughout
export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

// ============================================================================
// Row types
// ============================================================================
export type Profile = Database['public']['Tables']['profiles']['Row'];
export type Family = Database['public']['Tables']['families']['Row'];
export type FamilyMember = Database['public']['Tables']['family_members']['Row'];
export type PreparednessPlan = Database['public']['Tables']['preparedness_plans']['Row'];
export type ChecklistItem = Database['public']['Tables']['checklist_items']['Row'];
export type WeatherAlert = Database['public']['Tables']['weather_alerts']['Row'];
export type LocalizedAlert = Database['public']['Tables']['localized_alerts']['Row'];
export type Shelter = Database['public']['Tables']['shelters']['Row'];
export type EvacuationRoute = Database['public']['Tables']['evacuation_routes']['Row'];
export type SOSRequest = Database['public']['Tables']['sos_requests']['Row'];
export type CommunityReport = Database['public']['Tables']['community_reports']['Row'];
export type OfflineCacheManifest = Database['public']['Tables']['offline_cache_manifests']['Row'];
export type RiskScoreHistory = Database['public']['Tables']['risk_score_history']['Row'];

// ============================================================================
// Enum types
// ============================================================================
export type PreparednessPhase = Database['public']['Enums']['phase'];
export type ChecklistPriority = Database['public']['Enums']['priority'];
export type AlertSeverity = Database['public']['Enums']['alert_severity'];
export type EmergencyType = Database['public']['Enums']['emergency_type'];
export type SOSStatus = Database['public']['Enums']['sos_status'];
export type CommunityReportType = Database['public']['Enums']['report_type'];
export type CommunityReportSeverity = Database['public']['Enums']['report_severity'];
export type VerificationStatus = Database['public']['Enums']['verification_status'];
export type RoadCondition = Database['public']['Enums']['road_condition'];
export type SuitableFor = Database['public']['Enums']['suitable_for'];

// ============================================================================
// Additional type aliases
// ============================================================================
export type LanguageCode =
  | 'en' | 'hi' | 'mr' | 'gu' | 'bn' | 'ta' | 'te' | 'kn' | 'ml' | 'or' | 'pa' | 'as';

export type ChecklistCategory =
  | 'home_prep'
  | 'documents'
  | 'emergency_kit'
  | 'evacuation'
  | 'health'
  | 'communication';

export type SupportedLanguage = LanguageCode;

// ============================================================================
// Insert types
// ============================================================================
export type ProfileInsert = Database['public']['Tables']['profiles']['Insert'];
export type FamilyInsert = Database['public']['Tables']['families']['Insert'];
export type FamilyMemberInsert = Database['public']['Tables']['family_members']['Insert'];
export type PreparednessPlanInsert = Database['public']['Tables']['preparedness_plans']['Insert'];
export type ChecklistItemInsert = Database['public']['Tables']['checklist_items']['Insert'];
export type WeatherAlertInsert = Database['public']['Tables']['weather_alerts']['Insert'];
export type LocalizedAlertInsert = Database['public']['Tables']['localized_alerts']['Insert'];
export type ShelterInsert = Database['public']['Tables']['shelters']['Insert'];
export type EvacuationRouteInsert = Database['public']['Tables']['evacuation_routes']['Insert'];
export type SOSRequestInsert = Database['public']['Tables']['sos_requests']['Insert'];
export type CommunityReportInsert = Database['public']['Tables']['community_reports']['Insert'];
export type OfflineCacheManifestInsert = Database['public']['Tables']['offline_cache_manifests']['Insert'];
export type RiskScoreHistoryInsert = Database['public']['Tables']['risk_score_history']['Insert'];

// ============================================================================
// Update types
// ============================================================================
export type ProfileUpdate = Database['public']['Tables']['profiles']['Update'];
export type FamilyUpdate = Database['public']['Tables']['families']['Update'];
export type FamilyMemberUpdate = Database['public']['Tables']['family_members']['Update'];
export type PreparednessPlanUpdate = Database['public']['Tables']['preparedness_plans']['Update'];
export type ChecklistItemUpdate = Database['public']['Tables']['checklist_items']['Update'];
export type WeatherAlertUpdate = Database['public']['Tables']['weather_alerts']['Update'];
export type LocalizedAlertUpdate = Database['public']['Tables']['localized_alerts']['Update'];
export type ShelterUpdate = Database['public']['Tables']['shelters']['Update'];
export type EvacuationRouteUpdate = Database['public']['Tables']['evacuation_routes']['Update'];
export type SOSRequestUpdate = Database['public']['Tables']['sos_requests']['Update'];
export type CommunityReportUpdate = Database['public']['Tables']['community_reports']['Update'];
export type OfflineCacheManifestUpdate = Database['public']['Tables']['offline_cache_manifests']['Update'];
export type RiskScoreHistoryUpdate = Database['public']['Tables']['risk_score_history']['Update'];