import type { RiskScoreFactors } from './domain';
/**
 * GenAI types for LLM interactions: plan generation, alert localization, Q&A, risk explanation, image analysis, voice.
 * All prompts use strict schemas for structured output parsing.
 */

import type {
  Family,
  FamilyMember,
  PreparednessPhase,
  WeatherAlert,
  ChecklistPriority,
  ChecklistCategory,
} from './database';

/**
 * Supported Indian languages (12 + English)
 */
export type SupportedLanguage =
  | 'en'
  | 'hi'
  | 'mr'
  | 'gu'
  | 'bn'
  | 'ta'
  | 'te'
  | 'kn'
  | 'ml'
  | 'or'
  | 'pa'
  | 'as';

export const SUPPORTED_LANGUAGES: readonly SupportedLanguage[] = [
  'en',
  'hi',
  'mr',
  'gu',
  'bn',
  'ta',
  'te',
  'kn',
  'ml',
  'or',
  'pa',
  'as',
] as const;

export const LANGUAGE_NAMES: Record<SupportedLanguage, { name: string; nativeName: string }> = {
  en: { name: 'English', nativeName: 'English' },
  hi: { name: 'Hindi', nativeName: 'हिन्दी' },
  mr: { name: 'Marathi', nativeName: 'मराठी' },
  gu: { name: 'Gujarati', nativeName: 'ગુજરાતી' },
  bn: { name: 'Bengali', nativeName: 'বাংলা' },
  ta: { name: 'Tamil', nativeName: 'தமிழ்' },
  te: { name: 'Telugu', nativeName: 'తెలుగు' },
  kn: { name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  ml: { name: 'Malayalam', nativeName: 'മലയാളം' },
  or: { name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  pa: { name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  as: { name: 'Assamese', nativeName: 'অসমীয়া' },
};

/**
 * Input for personalized preparedness plan generation
 */
export interface PlanGenerationInput {
  family: Family;
  members: FamilyMember[];
  phase: PreparednessPhase;
  currentWeatherAlerts: WeatherAlert[];
  vulnerabilityScore: number; // 0.00-1.00
  housingType: string;
  hazardZones: string[];
  location: {
    district: string;
    ward?: string;
    lat: number;
    lng: number;
  };
  language: SupportedLanguage;
  previousPlanHash?: string; // for diff/regeneration
}

/**
 * Output schema for plan generation (strict JSON)
 */
export interface PlanGenerationOutput {
  plan: {
    summary: string;
    riskScore: number; // 0-100
    riskFactors: string[];
    phaseGuidance: Record<PreparednessPhase, string>;
  };
  checklist: ChecklistItemOutput[];
  emergencyContacts: EmergencyContactOutput[];
  metadata: PlanGenerationMetadata;
}

export interface ChecklistItemOutput {
  itemId: string; // UUID generated by GenAI for idempotency
  title: string;
  titleLocalized: Record<SupportedLanguage, string>;
  description: string;
  descriptionLocalized: Record<SupportedLanguage, string>;
  category: ChecklistCategory;
  priority: ChecklistPriority;
  phaseApplicability: PreparednessPhase[];
  estimatedTimeMinutes?: number;
  dependencies?: string[]; // itemIds that must be completed first
  locationSpecificGuidance?: string;
  locationSpecificGuidanceLocalized?: Record<SupportedLanguage, string>;
}

export interface EmergencyContactOutput {
  name: string;
  phone: string;
  type: 'police' | 'fire' | 'ambulance' | 'disaster_management' | 'shelter' | 'family' | 'other';
  priority: number;
  isVerified: boolean;
}

export interface PlanGenerationMetadata {
  generatedAt: string; // ISO 8601
  model: string;
  modelVersion: string;
  promptHash: string;
  tokensUsed: {
    prompt: number;
    completion: number;
  };
  latencyMs: number;
  confidenceScore: number; // 0-1
}

/**
 * Input for alert localization
 */
export interface AlertLocalizationInput {
  alert: WeatherAlert;
  family: Family;
  members: FamilyMember[];
  language: SupportedLanguage;
  currentPhase: PreparednessPhase;
  familyRiskScore?: number;
}

/**
 * Output for localized alert
 */
export interface AlertLocalizationOutput {
  title: string;
  description: string;
  actionItems: string[];
  urgencyScore: number; // 0-100
  urgencyLevel: 'immediate' | 'soon' | 'monitor';
  relevantPhases: PreparednessPhase[];
  metadata: {
    generatedAt: string;
    model: string;
    tokensUsed: { prompt: number; completion: number };
  };
}

/**
 * Input for citizen Q&A with GenAI
 */
export interface QAInput {
  question: string;
  language: SupportedLanguage;
  context: {
    family?: Family;
    members?: FamilyMember[];
    currentAlerts?: WeatherAlert[];
    currentPhase?: PreparednessPhase;
    location?: { district: string; ward?: string; lat: number; lng: number };
  };
  conversationHistory?: QAMessage[];
  useRAG: boolean; // whether to search official advisories
}

export interface QAMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
}

/**
 * Output for Q&A
 */
export interface QAOutput {
  answer: string;
  answerLocalized: Record<SupportedLanguage, string>;
  citations: QACitation[];
  confidence: number; // 0-1
  suggestedFollowUps: string[];
  metadata: {
    generatedAt: string;
    model: string;
    tokensUsed: { prompt: number; completion: number };
    usedRAG: boolean;
  };
}

export interface QACitation {
  source: 'IMD' | 'CWC' | 'NDMA' | 'ULB' | 'WHO' | 'RedCross' | 'other';
  title: string;
  url?: string;
  snippet: string;
  relevanceScore: number; // 0-1
}

/**
 * Input for risk score explanation
 */
export interface RiskExplanationInput {
  family: Family;
  members: FamilyMember[];
  riskScore: number;
  factors: RiskScoreFactors;
  currentAlerts: WeatherAlert[];
  language: SupportedLanguage;
  detailLevel: 'summary' | 'detailed' | 'technical';
}



/**
 * Output for risk explanation
 */
export interface RiskExplanationOutput {
  summary: string;
  summaryLocalized: Record<SupportedLanguage, string>;
  detailedBreakdown: RiskFactorExplanation[];
  recommendedActions: string[];
  visualAids?: VisualAid[];
  metadata: {
    generatedAt: string;
    model: string;
    tokensUsed: { prompt: number; completion: number };
  };
}

export interface RiskFactorExplanation {
  factor: keyof RiskScoreFactors;
  label: string;
  labelLocalized: Record<SupportedLanguage, string>;
  contribution: number; // percentage of total score
  explanation: string;
  explanationLocalized: Record<SupportedLanguage, string>;
  mitigationTips: string[];
  mitigationTipsLocalized: Record<SupportedLanguage, string[]>;
}

export interface VisualAid {
  type: 'chart' | 'map' | 'icon' | 'timeline';
  data: unknown;
  altText: string;
  altTextLocalized: Record<SupportedLanguage, string>;
}

/**
 * Input for image analysis
 */
export interface ImageAnalysisInput {
  imageBase64: string;
  mimeType: 'image/jpeg' | 'image/png' | 'image/webp';
  context: {
    lat: number;
    lng: number;
    timestamp: string;
    reporterNotes?: string;
  };
  analysisType: 'waterlogging_severity' | 'road_condition' | 'shelter_status' | 'damage_assessment';
  language: SupportedLanguage;
}

/**
 * Output for image analysis
 */
export interface ImageAnalysisOutput {
  analysisType: ImageAnalysisInput['analysisType'];
  severity: 'low' | 'medium' | 'high' | 'critical';
  confidence: number; // 0-1
  findings: ImageFinding[];
  recommendations: string[];
  recommendationsLocalized: Record<SupportedLanguage, string[]>;
  estimatedMetrics?: EstimatedMetrics;
  metadata: {
    generatedAt: string;
    model: string;
    tokensUsed: { prompt: number; completion: number };
  };
}

export interface ImageFinding {
  label: string;
  labelLocalized: Record<SupportedLanguage, string>;
  confidence: number;
  bbox?: { x: number; y: number; width: number; height: number }; // normalized 0-1
}

export interface EstimatedMetrics {
  waterDepthCm?: number;
  roadPassable?: boolean;
  occupancyPercentage?: number;
  damageLevel?: 'none' | 'minor' | 'moderate' | 'severe' | 'destroyed';
}

/**
 * Input for voice interaction
 */
export interface VoiceInteractionInput {
  audioBase64: string;
  mimeType: 'audio/webm' | 'audio/mp4' | 'audio/wav';
  language: SupportedLanguage;
  context: QAInput['context'];
  mode: 'stt' | 'tts' | 'conversation';
}

/**
 * Output for voice interaction
 */
export interface VoiceInteractionOutput {
  mode: VoiceInteractionInput['mode'];
  transcript?: string;
  transcriptLocalized?: Record<SupportedLanguage, string>;
  audioBase64?: string;
  responseText?: string;
  responseTextLocalized?: Record<SupportedLanguage, string>;
  intent?: VoiceIntent;
  metadata: {
    generatedAt: string;
    model: string;
    latencyMs: number;
  };
}

export interface VoiceIntent {
  type: 'ask_question' | 'report_issue' | 'request_sos' | 'get_plan' | 'get_alerts' | 'find_shelter' | 'unknown';
  confidence: number;
  entities: Record<string, unknown>;
}

/**
 * GenAI usage metrics
 */
export interface GenAiUsageMetrics {
  model: string;
  period: { start: string; end: string };
  requests: number;
  tokens: { prompt: number; completion: number; total: number };
  avgLatencyMs: number;
  errorRate: number;
  costUsd: number;
  byOperation: Record<string, { requests: number; tokens: number; costUsd: number }>;
}

/**
 * Prompt templates (stored as constants for versioning)
 */
export interface PromptTemplate {
  name: string;
  version: string;
  systemPrompt: string;
  userPromptTemplate: string;
  outputSchema: unknown; // JSON Schema
  temperature: number;
  maxTokens: number;
  model: string;
}

export const PROMPT_TEMPLATES: Record<string, PromptTemplate> = {
  plan_generation: {
    name: 'plan_generation',
    version: '1.0.0',
    systemPrompt: `You are an expert disaster preparedness assistant for Mumbai monsoon. Generate personalized, actionable family preparedness plans in the user's language. Follow the exact JSON schema.`,
    userPromptTemplate: `Generate a {phase} preparedness plan for a family in {district}, {ward}.
Family: {adults} adults, {children} children (<5), {elderly} elderly (>65), {vulnerable} with medical conditions
Housing: {housingType}, Hazard zones: {hazardZones}
Vulnerability score: {vulnerabilityScore}/1.00
Current weather alerts: {alertSummary}
Language: {language}`,
    outputSchema: {} as PlanGenerationOutput, // placeholder
    temperature: 0.3,
    maxTokens: 4000,
    model: 'gpt-4o-mini',
  },
  alert_localization: {
    name: 'alert_localization',
    version: '1.0.0',
    systemPrompt: `You are a disaster alert localization expert. Translate and personalize official weather alerts for specific families in their language with actionable steps.`,
    userPromptTemplate: `Localize this alert for a family:
Alert: {alertTitle} - {alertDescription}
Severity: {severity}
Family: {familySize} members, {vulnerableCount} vulnerable, {housingType} housing
Location: {district}, {ward}, hazard zones: {hazardZones}
Phase: {currentPhase}
Language: {language}`,
    outputSchema: {} as AlertLocalizationOutput,
    temperature: 0.2,
    maxTokens: 2000,
    model: 'gpt-4o-mini',
  },
  qa: {
    name: 'qa',
    version: '1.0.0',
    systemPrompt: `You are a helpful monsoon preparedness assistant. Answer citizen questions using official advisories (IMD, NDMA, ULB). Cite sources. Be concise and actionable.`,
    userPromptTemplate: `Question: {question}
Context: {contextSummary}
Language: {language}`,
    outputSchema: {} as QAOutput,
    temperature: 0.3,
    maxTokens: 3000,
    model: 'gpt-4o-mini',
  },
  risk_explanation: {
    name: 'risk_explanation',
    version: '1.0.0',
    systemPrompt: `You are a risk communication expert. Explain personalized risk scores clearly with visualizable breakdowns and mitigation tips.`,
    userPromptTemplate: `Explain this risk score: {riskScore}/100
Factors: Weather {weatherFactor}%, Vulnerability {vulnerabilityFactor}%, Preparedness {preparednessFactor}%, Housing {housingFactor}%
Current alerts: {alertSummary}
Family: {familySummary}
Language: {language}
Detail level: {detailLevel}`,
    outputSchema: {} as RiskExplanationOutput,
    temperature: 0.2,
    maxTokens: 3000,
    model: 'gpt-4o-mini',
  },
  image_analysis: {
    name: 'image_analysis',
    version: '1.0.0',
    systemPrompt: `You are a disaster image analysis expert. Assess monsoon-related images for severity and actionable insights.`,
    userPromptTemplate: `Analyze this {analysisType} image from lat:{lat}, lng:{lng} at {timestamp}.
Reporter notes: {reporterNotes}
Language: {language}`,
    outputSchema: {} as ImageAnalysisOutput,
    temperature: 0.1,
    maxTokens: 2000,
    model: 'gpt-4o',
  },
  voice_interaction: {
    name: 'voice_interaction',
    version: '1.0.0',
    systemPrompt: `You are a voice-first monsoon assistant for low-literacy users. Keep responses short, clear, and actionable.`,
    userPromptTemplate: `User said: {transcript}
Context: {contextSummary}
Language: {language}
Mode: {mode}`,
    outputSchema: {} as VoiceInteractionOutput,
    temperature: 0.3,
    maxTokens: 1500,
    model: 'gpt-4o-mini',
  },
};